// File: src/services/api.js
// THE ONLY FILE THAT SHOULD CHANGE when your FastAPI REST endpoints go live.
// Every function here currently resolves mock data after a short simulated
// delay. Each one has the real fetch() call written right below it, commented
// out — uncomment it, delete the mock block above it, and the rest of the
// app (which only ever calls these functions) needs zero changes.

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** Small helper for when the real backend is wired in — not used in mock mode. */
async function request(path, options = {}) {
  const res = await fetch(`${API_BASE_URL}${path}`, {
    headers: { 'Content-Type': 'application/json' },
    ...options,
  });
  if (!res.ok) throw new Error(`API error ${res.status} on ${path}`);
  return res.json();
}

/* ------------------------------------------------------------------ */
/*  Energy overview — feeds EnergyCard + BudgetCard on the Home page   */
/* ------------------------------------------------------------------ */
export async function getEnergyOverview() {
  await delay(250);
  return {
    totalKwh: 432.8,
    tariffPerUnit: 8, // ₹ per kWh, set on the Settings page
    budgetSpent: 4110, // ₹
    budgetLimit: 5000, // ₹
  };

  // Real version:
  // return request('/energy/overview');
}

/* ------------------------------------------------------------------ */
/*  Historical consumption — Daily/Weekly/Monthly tabs on the Home     */
/*  page chart. This is REST, not WebSocket — it should read from      */
/*  InfluxDB on the backend, not the live socket.                      */
/* ------------------------------------------------------------------ */
export async function getConsumptionHistory(timeframe) {
  await delay(300);

  if (timeframe === 'daily') {
    const pts = [];
    let cumulative = 0;
    for (let h = 0; h < 24; h++) {
      const base = h >= 7 && h <= 10 ? 0.9 : h >= 18 && h <= 22 ? 1.2 : 0.4;
      cumulative += base + Math.random() * 0.3;
      pts.push({ label: `${String(h).padStart(2, '0')}:00`, value: Math.round(cumulative * 10) / 10 });
    }
    return pts;
  }

  if (timeframe === 'weekly') {
    return ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((d) => ({
      label: d,
      value: Math.round((10 + Math.random() * 8) * 10) / 10,
    }));
  }

  // monthly
  const pts = [];
  for (let d = 1; d <= 30; d++) {
    pts.push({ label: String(d), value: Math.round((9 + Math.random() * 9) * 10) / 10 });
  }
  return pts;

  // Real version:
  // return request(`/energy/history?timeframe=${timeframe}`);
}

/* ------------------------------------------------------------------ */
/*  Socket control — SocketControlsCard                                */
/* ------------------------------------------------------------------ */
export async function getSocketStates() {
  await delay(200);
  return [
    { id: 'A', name: 'Socket A', on: true, watts: 1240 },
    { id: 'B', name: 'Socket B', on: true, watts: 85 },
  ];

  // Real version:
  // return request('/sockets');
}

export async function setSocketState(socketId, on) {
  await delay(150);
  return { id: socketId, on };

  // Real version — this one actually flips the ESP32 relay via the backend:
  // return request(`/sockets/${socketId}`, {
  //   method: 'PATCH',
  //   body: JSON.stringify({ on }),
  // });
}

/* ------------------------------------------------------------------ */
/*  AI energy summary — generated by Gemini on the backend, cached     */
/*  weekly. The frontend only ever reads the cached result.            */
/* ------------------------------------------------------------------ */
export async function getAiSummary() {
  await delay(400);
  return {
    period: 'Weekly',
    summary:
      "Usage peaked near 5.1 kW around 8 PM, mostly from Socket A. Overnight draw on Socket B suggests a device left in standby.",
    tip: "Shifting heavy loads on Socket A to off-peak hours could trim next month's bill by roughly 12%.",
    generatedAt: new Date().toISOString(),
  };

  // Real version:
  // return request('/ai/summary');
}

/* ------------------------------------------------------------------ */
/*  Settings — tariff rate, monthly budget goal, custom billing date   */
/* ------------------------------------------------------------------ */
export async function getSettings() {
  await delay(200);
  return {
    tariffPerUnit: 8, // ₹ per kWh
    monthlyBudgetGoal: 5000, // ₹
    billingDate: 1, // day of month (1–28) the billing cycle resets
  };

  // Real version:
  // return request('/settings');
}

export async function updateSettings(settings) {
  await delay(300);
  return { ...settings, updatedAt: new Date().toISOString() };

  // Real version:
  // return request('/settings', {
  //   method: 'PUT',
  //   body: JSON.stringify(settings),
  // });
}

/* ------------------------------------------------------------------ */
/*  Bill prediction — "Bill Prediction" card on Home. Extrapolates the */
/*  current cycle's pace out to the next Custom Billing Date.          */
/* ------------------------------------------------------------------ */
export async function getBillPrediction() {
  await delay(300);
  return {
    projectedKwh: 522.4,
    projectedCost: 5380, // ₹ — projected total for the full cycle
    daysRemainingInCycle: 9,
    vsBudget: 380, // ₹ over (positive) or under (negative) the budget goal
  };

  // Real version:
  // return request('/energy/bill-prediction');
}

/* ------------------------------------------------------------------ */
/*  Efficiency score — "Energy Efficiency Score" card on Home           */
/* ------------------------------------------------------------------ */
export async function getEfficiencyScore() {
  await delay(250);
  return {
    score: 78, // 0–100
    band: 'good', // 'excellent' | 'good' | 'needs-improvement'
    summary: 'Slightly high standby draw overnight is holding this back from Excellent.',
  };

  // Real version:
  // return request('/energy/efficiency-score');
}

/* ------------------------------------------------------------------ */
/*  Monthly history — History page. Static, backend-rolled summaries;  */
/*  no client-side reset logic — the backend closes out a cycle        */
/*  automatically on the Custom Billing Date from Settings.            */
/* ------------------------------------------------------------------ */
export async function getMonthlyHistory() {
  await delay(300);
  return [
    {
      id: '2026-07',
      label: 'July 2026',
      totalKwh: 468.2,
      totalCost: 3746,
      aiSummary: {
        summary:
          'Consumption ran steady through July, with a small peak in the last week likely tied to festival lighting.',
        tip: 'Socket B idled overnight most nights — worth checking what stayed plugged in.',
      },
    },
    {
      id: '2026-06',
      label: 'June 2026',
      totalKwh: 511.6,
      totalCost: 4093,
      aiSummary: {
        summary: 'A hot spell mid-month pushed Socket A well above its usual load for about ten days straight.',
        tip: 'Servicing or shading the AC unit on Socket A could meaningfully lower peak-month costs.',
      },
    },
    {
      id: '2026-05',
      label: 'May 2026',
      totalKwh: 402.9,
      totalCost: 3223,
      aiSummary: {
        summary: 'The lowest-usage month in this window, with no sustained peaks and steady evening-only load.',
        tip: 'This is close to your most efficient pace — worth treating as a benchmark month.',
      },
    },
  ];

  // Real version:
  // return request('/energy/history/monthly');
}
